---
baseurl: "https://pentacode.app/"
title: "Pentacode"
languageCode: "de-de"
metaDataFormat: "yaml"
pluralizelisttitles: false
params:
    get_started_url: "/#angebot"
    contact_url: "mailto://contact@pentacode.app"
